# Generated by Django 5.2.5 on 2025-08-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
