# Generated by Django 5.2.5 on 2025-08-26 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(null=True, verbose_name='Data da Sessão'),
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Hora de Término'),
        ),
        migrations.AddField(
            model_name='session',
            name='psychologist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='psychologist_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Hora de Início'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
